"""create learner skills table

Revision ID: 33923415f47c
Revises: 897c9faaaad8
Create Date: 2026-10-02 15:02:02.755206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33923415f47c'
down_revision = '897c9faaaad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_skills_user_id'), 'learner_skills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_skills_user_id'), table_name='learner_skills')
    op.drop_table('learner_skills')
    # ### end Alembic commands ###
