"""add ticket activities

Revision ID: 4b14f7c3b499
Revises: c22881040faf
Create Date: 2026-09-28 07:47:01.200417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b14f7c3b499'
down_revision = 'c22881040faf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_activities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_activities_created_at'), 'ticket_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_activities_ticket_id'), 'ticket_activities', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_activities_user_id'), 'ticket_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_activities_user_id'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_ticket_id'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_created_at'), table_name='ticket_activities')
    op.drop_table('ticket_activities')
    # ### end Alembic commands ###
