"""add learner skills

Revision ID: 78360eec3349
Revises: 4b14f7c3b499
Create Date: 2026-10-02 14:33:11.503029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78360eec3349'
down_revision = '4b14f7c3b499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
