"""create goal analyses table

Revision ID: 7b5e17d110b6
Revises: 931e1419098a
Create Date: 2026-10-09 21:58:21.400867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5e17d110b6'
down_revision = '931e1419098a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('learner_level', sa.String(length=50), nullable=False),
    sa.Column('skill_gaps', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('recommended_difficulty', sa.String(length=50), nullable=False),
    sa.Column('learning_sequence', sa.JSON(), nullable=False),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_analyses_goal_id'), 'goal_analyses', ['goal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_analyses_goal_id'), table_name='goal_analyses')
    op.drop_table('goal_analyses')
    # ### end Alembic commands ###
