"""add learner skills

Revision ID: 897c9faaaad8
Revises: 78360eec3349
Create Date: 2026-10-02 14:37:12.314632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897c9faaaad8'
down_revision = '78360eec3349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
