"""sync auth indexes and preferences constraint

Revision ID: d70008be2fd2
Revises: 3d2bd05e9089
Create Date: 2026-09-15 18:15:36.440400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70008be2fd2'
down_revision = '3d2bd05e9089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_otp_requests_user_id'), 'otp_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_user_preferences_user_id'), 'user_preferences', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_preferences_user_id'), 'user_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_otp_requests_user_id'), table_name='otp_requests')
    # ### end Alembic commands ###
